### ISSUE TITLE
[Bug]: lookup by block hash doesn't work

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/explorer#1070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SUMMARY

Pasting a block hash into the search bar doesn't work as expected

### STEPS TO REPRODUCE

1. Open https://explorer.oasis.io/
2. Paste `0xedd87e1b070dc3ab67639f155a4bb9928c57786659e80b4363819196f364aa48` into the search bar
3. See 'No Results Found'
4. Click on 'Try out a search: **Block**'
5. Takes me to completely unrelated block

### EXPECTED BEHAVIOR

Instead of 'No Results Found' it should either go directly to https://explorer.oasis.io/search?q=1357486 or show the block summary for the single result that I can click on to take me to that page.

The 'Try out a search' links at the bottom are confusing, I assumed that I was searching for the wrong kind of thing, and clicking on the link would take me to the block.

**Comment by csillag** [comment]
I'm happy to take this on, but I think this needs some Nexus support first.

**Comment by csillag** [comment]
Nexus PR is coming in here: https://github.com/oasisprotocol/nexus/pull/581

**Comment by csillag** [comment]
> The 'Try out a search' links at the bottom are confusing, I assumed that I was searching for the wrong kind of thing, and clicking on the link would take me to the block.

The issue described in the above part of the report has been solved by #1080.

**Comment by CedarMist** [comment]
Awesome thank you :D 

Being able to search for blockhashes specifically will make this more useful on a day to day basis as a dev tool, as looking up by block hash is a common thing to do when debugging.

**Comment by csillag** [comment]
> Pasting a block hash into the search bar doesn't work as expected

This has been solved by #1081.

However, to be able to use it on https://explorer.oasis.io/, we will need for the Nexus team to deploy the latest version to production. (I'm keeping this ticket open until that happens.)
