### ISSUE TITLE
Fix transaction details gas

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/explorer#130]
What should transaction details show for gas?

- API:
  https://index-staging.oasislabs.com/v1/emerald/transactions/f89c23ce07e17c503735f8f6393ae30592ceb7c39d81c24990aff15b5dae1103
  "fee": "800000000000000000",
  "gas_limit": 8000000,

- Blockscout:
  https://explorer.emerald.oasis.dev/tx/0xe976b0d3fadf1197ab8549f5995606605414df94273322a51a57e41ea2ad3855/internal-transactions
  Transaction Fee  0.2979207 ROSE
  Gas Price  100 Gwei
  Gas Limit  8,000,000
  Max Fee per Gas  100 Gwei
  Max Priority Fee per Gas  100 Gwei

- Current explorer incorrectly shows:
  http://localhost:1234/emerald/transactions/f89c23ce07e17c503735f8f6393ae30592ceb7c39d81c24990aff15b5dae1103
  Txn Fee  800000000000000000 ROSE
  Gas limit  8000000 ROSE

> - oasisscan:
>   https://www.oasisscan.com/paratimes/transactions/0xe976b0d3fadf1197ab8549f5995606605414df94273322a51a57e41ea2ad3855?runtime=000000000000000000000000000000000000000000000000e2eaa99fc008f87f
>   "gasPrice": 100000000000,
>   "gasLimit": 8000000,
>

**Comment by mitjat** [comment]
IIUC, from the backend perspective there are ~two~ 1.5 issues:
- Documentation bug/deficiency, where we should state that the fee is in consensus/runtime base units ([here](https://github.com/oasisprotocol/oasis-indexer/blob/96a140711e77d460da56a0e5f5bf4e6bbaf8283b/api/spec/v1.yaml#L1124-L1124) for consensus and ... oh, actually paratime fee units are already documented [here](https://github.com/oasisprotocol/oasis-indexer/blob/96a140711e77d460da56a0e5f5bf4e6bbaf8283b/api/spec/v1.yaml#L1915-L1915))
- The fee value is not reported correctly. Although ... maybe blockscout is wrong here? Our code is [extremely straightforward](https://github.com/oasisprotocol/oasis-indexer/blob/96a140711e77d460da56a0e5f5bf4e6bbaf8283b/api/v1/logic.go#L47-L47), and the value varies a lot across txs: `curl 'https://index.oasislabs.com/v1/emerald/transactions' | jq '.transactions[].fee'`. OTOH, 800000000000000000/1e16 = 80 ROSE seems like a crazy high fee.

**Comment by lukaw3d** [comment]
@mitjat emerald native denomination is 1e18, so 0.8 ROSE.
Then gas price 0.8 / 8000000 = 0.0000001 ROSE per gas unit = "100 Gwei"

**Comment by lukaw3d** [comment]
(added oasisscan to the comparison)

**Comment by mitjat** [comment]
Thank you for the 1e18 correction. That's more reasonable :). Also, the fact that the gas price works out to 100Gwei (same as reported by blockscout) using indexer data is encouraging.
I guess it is just the blockscout fee that's wrong then? Because with their fee and gas limit, you cannot derive their 100Gwei gas price.
Oasisscan doesn't parse/show the fee.

**Comment by lukaw3d** [comment]
blockscout looks correct to me :shrug:

a | b
--- | ---
Gas Limit | 8,000,000
fee limit (not shown) | 0.8 ROSE (= fee / 1e18)
Gas Price | 100 ~Gwei~ base units (= fee limit / gas limit)
Gas Used by Transaction | 2,979,207
Transaction Fee | 0.2979207 ROSE (= used gas * gas price)

**Comment by mitjat** [comment]
Thanks for the explanation/reasoning again. I assumed that the submit-time-specified fee was charged regardless of the actual gas used. I asked in https://oasis-labs.slack.com/archives/CHTNKCRL0/p1676545195798179 (see also my reasoning there).

Anyway, the answer from Jernej is:
> it depends on what is being called:
> - for EVM it is charged based on actual usage (so the charge can be less)
> - all other txs (consensus and non-EVM SDK) will charge the entire fee
