### ISSUE TITLE
Fix displaying ERC-20 balances

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/explorer#131]
Current explorer incorrectly shows balances in base units
https://lw-oasis-explorer-frontend.pages.dev/emerald/account/0xba504818fdd8d3dba2ef8fd9b4f4d5c71ad1d1d3/tokens/erc-20

Name | Smart Contract | Balance | Ticker
-- | -- | -- | --
FTP | oasis1qpssvkplnlpzdvwxpgmrhf9j5lkyvaylcvujhjhg | 437325438367711264207872 | FTP
YUZU | oasis1qzk2y3kvp7000qck8zjsmwadhy3lumnmdys20x3z | 177611800000000000000000 | YUZU
fROSE | oasis1qrmtfytxk3exv60rpkv8p8ve99sf3kzp8u9ng4gq | 1989047 | fROSE
YUZU | oasis1qqz8706pmf38wmptl6dkcaec8yykw0rvfv7ql6fc | -392908390000000000000001 | YUZU

Use token_decimals.

**Comment by buberdds** [comment]
Closed via https://github.com/oasisprotocol/explorer/pull/135
