### ISSUE TITLE
Fix ShowMoreTokensLink linking to empty ERC-721

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/explorer#133]
https://lw-oasis-explorer-frontend.pages.dev/emerald/account/0xba504818fdd8d3dba2ef8fd9b4f4d5c71ad1d1d3
- Click "+1 more" in EVM tokens
- Opens empty ERC-721
- expected it to show 4th ERC-20

**Comment by buberdds** [comment]
Closed via https://github.com/oasisprotocol/explorer/pull/135
