### ISSUE TITLE
[Bug]: Homepage search in mobile footer

### ISSUE THREAD

**Issue by buberdds** [oasisprotocol/explorer#1403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### STEPS TO REPRODUCE

1) It should be hidden on mobile
2) If it has to be visible it cannot overlap mobile layer tooltip

![Screenshot from 2024-05-09 09-23-47](https://github.com/oasisprotocol/explorer/assets/891392/529a0b2e-463b-4ac6-815f-25fccc382c24)

**Comment by csillag** [comment]
https://app.clickup.com/t/8694h28bx also describes the same issue.

**Comment by lukaw3d** [comment]
Fixed by https://github.com/oasisprotocol/explorer/issues/1403
