### ISSUE TITLE
UX/UI Design Change Report

### ISSUE THREAD

**Issue by donouwens** [oasisprotocol/explorer#165]
---
#### SUMMARY

name: "title of issue"
about: "short description of issue"'
labels: 'ux/ui design'
assignees: '@donouwens'

---

#### ISSUE TYPE
- UX/UI Design Change Report

#### URGENCY
Is this issue blocking your progress?
- [ ] High
- [ ] Medium
- [ ] Low
- [ ] I don't know

#### PRODUCT ENVIRONMENT
Provide all relevant information below as to where the issue occurs within the product
```paste below

```

#### DESCRIPTION OF ISSUE
Describe the issue itself. Be as detailed as possible, preferably add a screenshot or recording to explain the issue further
```paste below

```

#### DEVICE / VIEWPORT
Share whether this occurs on desktop, mobile or both
- [ ] Desktop
- [ ] Mobile
- [ ] Both

#### STEPS TO REPRODUCE
Describe exactly how to reproduce the issue
```paste below

```

#### ALTERNATIVES AND SUGGESTIONS
Share any suggestions on how to solve the issue -_optional_-
```paste below

```

**Comment by lukaw3d** [comment]
Added in https://github.com/oasisprotocol/explorer/pull/166
