### ISSUE TITLE
How to find the same transaction in other explorers?

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/explorer#169]
e.g. https://lw-oasis-explorer-frontend.pages.dev/emerald/transactions/1ada4eb14e50d7c5426f707b6d636e2222280308f09356c1cb2c14503fe927e3

Issue is that Oasis Network Explorer currently uses tx.hash, not tx.eth_hash like other explorers

**Comment by Andrew7234** [comment]
https://github.com/oasisprotocol/oasis-indexer/pull/315 added support for looking up runtime transactions by either oasis hash or eth hash, does this help?

**Comment by mitjat** [comment]
In case it matters: the indexer endpoint https://index-staging.oasislabs.com/v1/emerald/transactions/:hash works for both Oasis and eth hashes.

**Comment by lukaw3d** [comment]
Yaay, that's finally deployed!
