### ISSUE TITLE
[Bug]: If API is broken we only detect it on homepage

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/explorer#356]
### URGENCY

- [ ] High
- [ ] Medium
- [X] Low
- [ ] I don't know

### DESCRIPTION OF ISSUE

| Home Page | Emerald dashboard |
| --- | --- |
| ![oasis-explorer pages dev_](https://user-images.githubusercontent.com/3758846/235970892-437547cb-4a2e-4ca0-a209-a4eef180472f.png) | ![oasis-explorer pages dev_ (1)](https://user-images.githubusercontent.com/3758846/235970895-fcc3e250-1b4d-4ed3-80b0-47ee40c3db6b.png) |

### DEVICE / VIEWPORT

- [X] Desktop
- [X] Mobile

### STEPS TO REPRODUCE

Open explorer with intentionally broken API: https://9543da24.oasis-explorer.pages.dev/emerald (deployed from https://github.com/oasisprotocol/explorer/commit/0a22166922b9fcb0235d203e8ae68ba9d0f736fe)

**Comment by lukaw3d** [comment]
Yes, thanks!
TODO: implement to match the mocks

**Comment by lukaw3d** [comment]
TODO: should we use getRuntimeStatus on homepage too?

**Comment by csillag** [comment]
> TODO: should we use getRuntimeStatus on homepage too?

Do you mean the Dashboards?

**Comment by csillag** [comment]
TODO: make sure to track the status of the correct deployment (TestNet vs MainNet)

**Comment by lukaw3d** [comment]
> 

That too;
I think Homepage should probably check:
- getStatus(mainnet /* consensus */)
- getRuntimeStatus(mainnet, emerald)
- getRuntimeStatus(mainnet, sapphire)

Mainnet Emerald Dashboard should check:
- getRuntimeStatus(mainnet, emerald)

**Comment by csillag** [comment]
See #462.

**Comment by csillag** [comment]
This has already been implemented. Closing.
