### ISSUE TITLE
[Bug]: Don't show account search result if returned account is empty

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/explorer#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### STEPS TO REPRODUCE

https://explorer.dev.oasis.io/search?q=0xBA504818FdD8D3dBA2Ef8fD9B4F4D5c71aD1d1D3
![image](https://github.com/oasisprotocol/explorer/assets/3758846/1a74e413-d2ab-4d5a-a976-9eb17e46aa3b)

**Comment by csillag** [comment]
What is a good definition of empty?

0 transactions? Or do we also have to look at other things?

**Comment by lukaw3d** [comment]
To be safe I'd check all we get:
```
balances: [],
evm_balances: [],
stats: {num_txns: 0, total_received: "0", total_sent: "0"}
```
