### ISSUE TITLE
[Bug]: Status of failed consensus deposits is not communicated

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/explorer#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SUMMARY

When a consensus deposit fails, the explorer does not indicate that.

### STEPS TO REPRODUCE

1. Create a deposit transaction in the runtime, e.g. using the CLI, such that the deposit will in fact fail (e.g. because the user does not have enough allowance or balance in the consensus layer). For example I used `oasis account deposit 10000`.
2. The CLI will report that the deposit transaction has succeeded, but the deposit has in fact failed (this is only known in the next round):
```
Broadcasting transaction...
Transaction included in block successfully.
Round:            550814
Transaction hash: c72d51780c9db7614fb4419d4c82a711ac0c3a430f2737e1f38961d7d019229a
Execution successful.
Waiting for deposit result...
Error: deposit failed with error code 5 from module staking
```
3. Looking at the [block explorer for this transaction](https://explorer.stg.oasis.io/mainnet/sapphire/tx/c72d51780c9db7614fb4419d4c82a711ac0c3a430f2737e1f38961d7d019229a) it just shows success as status. While this is technically correct when showing the status of the transaction itself, the deposit itself failed and this is not indicated anywhere on the explorer.

### EXPECTED BEHAVIOR

Some indication that the deposit itself failed even though the transaction succeeded.

**Comment by lukaw3d** [comment]
@donouwens with current API we can not tell if "but the deposit failed" (an event in the next block). If we could tell then I would argue for red color schema.

more accurate message example:
![image](https://github.com/oasisprotocol/explorer/assets/3758846/38877f68-8a02-4a9c-b373-093d435768e8)

**Comment by kostko** [comment]
I think this looks ok. For the message it would be great if we could say (for deposits): "Deposit has started, final result will be known in the next block." or similar. Then instead of "Partial success" it could also say "Started" or similar.

**Comment by ptrus** [comment]
Starting with https://github.com/oasisprotocol/nexus/pull/820 Nexus now handles these transactions (see the changelog for description on how it's handled).

It also works on explorer without additional changes. The transaction result will be marked as 'unknown'  until the event is received, and then it will be marked as either successful or failed.

However it would be great to also handle this on the explorer side and display the nice messages/icons as were discussed above.

**Comment by lukaw3d** [comment]
current solution could be confusing: our tx status doesn't match grpc and oasisscan.

And we only show caveats while status is pending

**Comment by lukaw3d** [comment]
I was just confused in sapphire depositing dApp - it didn't detect a tx failure it just got stuck. But explorer showed a [failed transaction](https://explorer.dev.oasis.io/testnet/sapphire/tx/27b401ef7722dd15ff66af534318644ce81cb78ba9c109f84f4e2fcb4d7f6303). But then I found a failed event in the next block. So grpc must had returned success. (and dapp relies on balance change instead of events to confirm the second step of depositing)
