### ISSUE TITLE
[Feature]: Conform to EIP-3091

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/explorer#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SUMMARY

Add standardized explorer routes defined in EIP-3091 so we can hook it with Metamask and other Ethereum services

### DESCRIPTION

See https://eips.ethereum.org/EIPS/eip-3091 for details. This is also a requirement, if we want to replace existing blockscout explorers in the official Ethereum chain list: https://github.com/ethereum-lists/chains

One way to do this is for example to use `<BLOCK_EXPORER_URL>` as `https://explorer.stg.oasis.io/mainnet/sapphire` and make aliases for:
- `block` -> `blocks`,
- `tx` -> `transactions`,
- `address` -> `account`,
- `token/0x...` -> `address/0x...` alias (for now until we get proper home page for the token)

**Comment by csillag** [comment]
Why aliases, instead of simply changing those paths to mach the specs?

**Comment by matevz** [comment]
> Why aliases, instead of simply changing those paths to mach the specs?

Sure, was just suggesting so we don't break anything that exists already ;)

**Comment by csillag** [comment]
Fortunately this has never been publicly advertised, so we don't have any contract (or expectation) to keep the current URLs stable.

**Comment by csillag** [comment]
I am unsure about the token part. About the rest, would this work? https://9da8918c.oasis-explorer.pages.dev/

**Comment by csillag** [comment]
I think this is mostly done now. The token support is not fully there, but we are building it up in small increments.
