### ISSUE TITLE
Can we bring back stable Cloudflare preview URLs

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/explorer#561]
When pushing commits to a PR, the preview URL keeps changing. This means I can't link to a stable preview URL that demos a new feature in latest state of the PR

Before https://github.com/oasisprotocol/explorer/pull/289 cloudflare-pages bot would include a stable `Branch Preview URL:` e.g.
<table><tr><td><strong>Latest commit:</strong> </td><td>
<code>cfe1f45</code>
</td></tr>
<tr><td><strong>Status:</strong></td><td>&nbsp;✅&nbsp; Deploy successful!</td></tr>
<tr><td><strong>Preview URL:</strong></td><td>
<a href='https://27574a63.oasis-explorer.pages.dev'>https://27574a63.oasis-explorer.pages.dev</a>
</td></tr>
<tr><td><strong>Branch Preview URL:</strong></td><td>
<a href='https://mz-cloudflare.oasis-explorer.pages.dev'>https://mz-cloudflare.oasis-explorer.pages.dev</a>
</td></tr>
</table>

**Comment by csillag** [comment]
➕ 
👍🏻

**Comment by buberdds** [comment]
1) Github action expose alias that in theory returns branch preview url. The problem is that it's buggy so it returns sometimes preview url and sometimes correct branch url. We can add it and wait for upstream fixes.


2) We can also create build preview url manually, but that won't be super reliable too. CloudFlare truncates branch names in the subdomain and replaces some chars `/` -> '-' not sure about all possible cases.

**Comment by lukaw3d** [comment]
maybe branch preview is broken because of https://github.com/oasisprotocol/explorer/blob/a4943a0e71bafa071c6f87a95951c3fbac77de32/.github/workflows/cloudflare-pages.yml#L44-L46

**Comment by buberdds** [comment]
Yeah, but we need it if we want a correct hash in a footer. As a workaround we can provide a branch name to action params. https://github.com/buberdds/explorer/blob/master/.github/workflows/cloudflare-pages.yml#L78
output 
https://github.com/buberdds/explorer/pull/110 

I had a few deploys with a wrong URL even if branch URL was correct in CF dashboard. Anyway, I will do more tests now.

Related issues:
```
https://github.com/cloudflare/pages-action/pull/40
https://github.com/cloudflare/pages-action/issues/18
https://github.com/cloudflare/pages-action/issues/29
etc
```

**Comment by lukaw3d** [comment]
Fixed by https://github.com/oasisprotocol/explorer/pull/1537
