### ISSUE TITLE
[UX]: Improve copy of "Undefined" token supply

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/explorer#739]
### URGENCY

- [ ] High
- [ ] Medium
- [X] Low
- [X] I don't know

### PRODUCT ENVIRONMENT

Staging

#### Description

The copy for "Undefined" token supply can probably be replaced with "Unknown" or some other variant.

<img width="1552" alt="image" src="https://github.com/oasisprotocol/explorer/assets/4441690/a0a67a0c-d2cf-4dae-b040-f8d2744a1cb0">

### DEVICE / VIEWPORT

- [X] Desktop
- [ ] Mobile

### STEPS TO REPRODUCE

1. Navigate to https://explorer.dev.oasis.io/mainnet/sapphire/token/0x998633BDF6eE32A9CcA6c9A247F428596e8e65d8
2. See "Undefined"

### ALTERNATIVES AND SUGGESTIONS

"Unknown" or "Unlimited" or "Arbitrarily large"

**Comment by tjanez** [comment]
I would propose an unobtrusive "-" like we do for "Active Nodes" panel if we don't have the data from the backend.

**Comment by csillag** [comment]
OK, #742 will solve this.

**Comment by csillag** [comment]
Closed via https://github.com/oasisprotocol/explorer/pull/742.
